apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: bash
  name: bash
spec:
  volumes:
    - name: secret-vol
      secret:
        secretName: secret1
  containers:
  - image: bash
    name: bash
    resources: {}
    command:
      - /bin/sh
      - -c
      - sleep 3600
    volumeMounts:
      - name: secret-vol
        mountPath: /tmp/secret1
    envFrom:
      - configMapRef:
          name: config-map-example
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
