apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx-service
  namespace: k8s-challenge-2-a
spec:
  ports:
  - port: 4444
    protocol: TCP
    targetPort: 80
  type: ClusterIP
  selector:
    run: nginx
status:
  loadBalancer: {}
