apiVersion: v1
kind: Pod
metadata:
        name: bash-pod
        namespace: default
        labels:
                app: bash
                my-label: test
spec:
        restartPolicy: Never
        containers:
                - name: bash-container
                  image: bash
                  imagePullPolicy: IfNotPresent
                  command:
                          - /bin/sh
                          - -c
                          - hostname > /tmp/hostname && sleep 30

