apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: "50Mi"
  hostPath:
    path: /tmp/k8s-challenge-3
