apiVersion: v1
kind: PersistentVolumeClaim
metadata:
        name: local-pvc
spec:
        storageClassName: default
        accessModes:
                - ReadWriteOnce
        resources:
                requests:
                        storage: "40Mi"
